#!/bin/sh

pushd ~/dotfiles

# -t defines the target directory, so where the symlinks should be created
# -DS means, stow should first delete old symlinks and then create new ones from the given stow directory
stow -t ~ -DS home
stow -t ~/.config -DS .config

popd
