#!/bin/sh

pushd ~/dotfiles

# -t defines the target directory, so where the symlinks should be created
# -DS means, stow should first delete old symlinks and then create new ones from the given stow directory
stow -t ~ -DS home

mkdir -p ~/.config
stow -t ~/.config -DS config

mkdir -p ~/.local/bin
stow -t ~/.local/bin -DS scripts

popd
